version: '3'
services:
  app:
    build: ./client/
    restart: always
    image: castelli_app
    expose:
      - 80
    environment:
      VIRTUAL_HOST: ${NGINX_DOMAIN}
      LETSENCRYPT_HOST: ${NGINX_DOMAIN}
      LETSENCRYPT_EMAIL: ${NGINX_EMAIL}
    
  storybook:
    build:
      context: ./client/
      dockerfile: Dockerfile-storybook
    restart: always
    image: castelli_storybook
    expose:
      - 2001
    environment:
      API_HOST: ${NGINX_DOMAIN}
      API_PORTS: 2001

networks:
    default:
        external:
            name: nginx-proxy
