version: '3'
services:
  app:
    build: ./client/
    restart: always
    image: castelli_app
    expose:
      - 80
    environment:
      VIRTUAL_HOST: ${NGINX_DOMAIN}
      LETSENCRYPT_HOST: ${NGINX_DOMAIN}
      LETSENCRYPT_EMAIL: ${NGINX_EMAIL}

networks:
    default:
        external:
            name: nginx-proxy
